### PR TITLE
ACA Weekly Report initial draft

### PR DESCRIPTION
**Pull request by jeanconn**
This PR includes code to make a weekly report.  This initial draft:

- collects kadi manvrs over the reporting interval
- finds the associated proseco star catalogs (for both catalog data and predictions)
- collects the observed fid, acq, guide data for the observation/manvr
- creates formatted catalog tables with red marking for stars and fids with unexpected values
- checks the observation t_ccd against the predictions
- looks for other kinds of anomalies such as high background or low Kalman star intervals
- makes a formatted table/report with the collected data and jinja2 templates

The in-progress report is available at 

https://cxc.cfa.harvard.edu/mta/ASPECT/aca_weekly_report/

To-do items :

- [ ] Put appropriate catalog row and observation text warnings on the detail page
   - [ ] document the catalog row and observation tests (may be self-documenting with above item)
- [ ] fix mica guide stats issues especially missing data and observations where all stars show low fraction
- [ ] create mica fid stats to remove sybase dependency
- [ ] put name hrefs on detail page to link directly (on a guide, fid, acq warning for example)
- [ ] improve titles / templates on detail and main page
- [ ] consider a system for archived weekly reports and navigation between them (for now doing the last week and the last quarter as two separate reports)
- [ ] email warnings on new entries in the table with interesting warnings
- [ ] try to remove duplication in layout/formatting code for the star catalogs and the full top-level table

### CODE REVIEW

**Comment by jeanconn** [comment]
I see my weekly notes say "sprint forward on critical issues" but I don't know which ones were considered critical.

**Comment by taldcroft** [comment]
Priorities:

- fix mica guide stats issues especially missing data and observations where all stars show low fraction: *Not clear what this means, but I get the impression that the tool can show misleading information? That would be bad, but your judgement.*
- create mica fid stats to remove sybase dependency: *it needs to work on shiny, but maybe this is a non-issue.*
- consider a system for archived weekly reports and navigation between them
- email warnings on new entries in the table with interesting warnings

**Comment by jeanconn** [comment]
I think all of those priorities are fine to address as separate issues.  The mica issue is actually a mica problem.  The fid_stats should work in a shiny with production perl packages.

**Comment by taldcroft** [comment]
OK to push those last two off to issues, but they should be addressed with a high priority in order to make this actually useful to us in our normal workflow (of being generally busy and benefitting from push notifications to email).

**Pull request merged**
